// <auto-generated />
namespace ProyectoFinal.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agregueParamedic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregueParamedic));
        
        string IMigrationMetadata.Id
        {
            get { return "201311240007118_agregueParamedic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
